const prompt = [
// --- le prompt maitre aiMARKET, tel que Max l'a ecrit, sans retouche
MAITRE,
'',
'=== 0. VARIABLES DE CETTE ETUDE ===',
'Date de l etude : ' + date,
'Pays principal : France',
'Zone commerciale : France + Europe',
'Categorie : ' + libelleCat,
'Slug categorie : ' + categorie,
'Theme analyse : ' + libelleTheme,
'Slug theme : ' + theme,
'',
'=== COMPLEMENT PIPELINE — PRIORITAIRE SUR LE RESTE ===',
'Tu ne navigues pas : toute ta matiere est fournie plus bas. Les catalogues',
'ci-dessous ont ete releves automatiquement pour cette etude. Ils remplacent',
'la recherche web demandee au point 1.1 du prompt maitre.',
'',
'REGLE URL — OBLIGATOIRE SUR LES 20 LIGNES.',
'Le client achete de l IMPORT AUTOMATIQUE : une ligne sans URL ne lui sert a rien.',
'supplier_url est TOUJOURS rempli, avec une adresse prise dans le CATALOGUE',
'FOURNISSEURS [F..]. Tu ne fabriques aucune adresse, et tu n en laisses aucune vide.',
'Privilegie les entrees de type "fiche" : elles sont listees en premier et',
'portent le nom du modele entre crochets. Une entree "liste" n est prise que si',
'aucune fiche ne correspond — un flux de scraping par extension la traitera',
'produit par produit derriere. N utilise jamais deux fois la meme adresse tant',
'qu il en reste de disponibles.',
'Ajoute a chaque produit le champ url_type : "fiche" ou "liste".',
'Ajoute a chaque produit le champ import : "url" si la fiche se lit a l adresse,',
'"extension" si la page se construit en JavaScript (AliExpress, Temu, Alibaba,',
'Shein, 1688), "api" pour un fournisseur relie par cle.',
'',
'REGLE IMAGE — OBLIGATOIRE SUR LES 20 LIGNES.',
'Ajoute a chaque produit le champ image_url, pris dans le CATALOGUE MARCHAND',
'[C..], celui du produit le plus proche. Ces images illustrent les fiches et les',
'articles. Tu ne fabriques aucune adresse d image.',
'',
'REGLE SOURCES BLOQUEES.',
'Les pages listees en SOURCES BLOQUEES n ont pas pu etre lues. Reporte-les',
'telles quelles dans la section 14 et dans la cle sources_bloquees du JSON.',
'Ne comble jamais ce qu elles auraient pu contenir.',
'',
'=== FORMAT DE SORTIE — IMPERATIF ===',
'Tu produis DEUX blocs et rien d autre, dans cet ordre, separes par une ligne',
'contenant exactement <<<JSON>>>.',
'',
'BLOC 1 : la ligne <<<MARKDOWN>>> seule, puis un en-tete YAML entre --- portant',
'type: aimarket, date, categorie, theme, titre, agent, marche_revente, sourcing,',
'produits, sources, sources_bloquees. Puis le rapport Markdown complet avec les',
'16 sections et les 5 tableaux obligatoires du prompt maitre.',
'',
'BLOC 2 : apres <<<JSON>>>, le JSON complet du point 9 du prompt maitre, valide,',
'sans balise de code, avec les trois champs ajoutes ci-dessus (url_type, import,',
'image_url) dans chaque produit, plus la cle sources_bloquees.',
'',
'=== CATALOGUE FOURNISSEURS (' + fournisseurs.length + ' adresses reelles) ===',
'C est la seule source autorisee pour supplier_url.',
listeFournisseurs,
'',
'=== CATALOGUE MARCHAND (' + catalogue.length + ' offres reelles, prix France) ===',
'Source des prix de revente constates ET des images produit.',
listeCatalogue,
'',
'=== SOURCES BLOQUEES (a reporter telles quelles) ===',
listeBloquees,
'',
'=== SOURCES LUES (' + pages.length + ' pages) ===',
corpus,
].join('\\n');
